Skip dynamic render path check for renderables
presidentbeef/brakeman pull request #1578
Opened 2021-03-18 04:12 UTC by bradparker

[Rails 6.1 now supports passing `Renderable`s to `render`](https://github.com/rails/rails/blob/b5b078cd99b0107fd8e31ff619578e5321182e0a/actionview/lib/action_view/template/renderable.rb).

A renderable is anything that responds to `render_in`. This means we can
now expect to see `render(SomeRenderableClass.new(some_parameter))`. A
new library for building Rails UIs out of components, ViewComponent, is
growing in popularity and makes use of this new `render_in` API.

Closes https://github.com/presidentbeef/brakeman/issues/1529.

2021-03-18 04:15 UTC, bradparker commented on lib/brakeman/checks/check_render.rb
> +  def method_defined? class_name, name, seen = []
I'm not sure about where best to put this, it feels too general too be scoped to only checking render calls. I also wanted to search `#includes` for `render_in` but the collection was always empty for my test components. I could see includes being populated for models but not for libs ... I could look better into how to populate includes? However, without that I _think_ this should address the ViewComponent use case as it looks like `render_in` is defined on `ViewComponent::Base`.

2021-03-18 18:41 UTC, presidentbeef commented
Hi @bradparker! Wow thanks for taking a swing at this! 🙏 

I think I have some pending changes that will help with method lookup.

I can't look too deeply at this PR right now but will follow up in the next few days!

2021-03-18 22:30 UTC, bradparker commented
> I think I have some pending changes that will help with method lookup.

Rad, thanks.

> I can't look too deeply at this PR right now but will follow up in the next few days!

No problem :). I feel like I'm probably missing some things so I really appreciate you taking the time, when ever you might have it, to have a look.

2021-05-20 23:20 UTC, bradparker commented
Ah, right. So, silly me, I've checked this in our code base just now. I didn't realize that Brakeman doesn't index dependencies so this doesn't quite work. It looks up `ViewComponent::Base` but can't find it so doesn't identify ViewComponents as renderables ... perhaps it would be possible to configure some class names as "renderables" if you're not comfortable adding specific handling for ViewComponent?

2021-05-20 23:58 UTC, bradparker commented
https://github.com/presidentbeef/brakeman/pull/1578/commits/8fe395edeb000b6f170f7f7093d31c392f41b7cf is a perhaps a proof of concept for handling ViewComponent specially. I've plugged that into our code base and it's removed all the ViewComponent related 'dynamic render path' false positives.

2021-05-27 14:09 UTC, presidentbeef commented on lib/brakeman/checks/check_render.rb
> +  def method_defined? start, name
Check out `Tracker#find_method` I just merged from https://github.com/presidentbeef/brakeman/pull/1596 I think it takes care of this.

2021-05-27 14:09 UTC, presidentbeef commented on lib/brakeman/checks/check_render.rb
> +      return true if class_name == :"ViewComponent::Base"
I think you can use `Collection#ancestor?` for this:

```ruby
klass = tracker.find_class(class_name)
klass.ancestor? :"ViewComponent::Base"
```

2021-05-27 14:11 UTC, presidentbeef commented
> [8fe395e](https://github.com/presidentbeef/brakeman/commit/8fe395edeb000b6f170f7f7093d31c392f41b7cf) is a perhaps a proof of concept for handling ViewComponent specially. I've plugged that into our code base and it's removed all the ViewComponent related 'dynamic render path' false positives.

That seems totally reasonable to me.

2021-06-02 19:57 UTC, presidentbeef requested changes

2021-06-02 19:57 UTC, presidentbeef commented on lib/brakeman/checks/check_render.rb
> +    return false unless call?(exp) and sexp?(exp.target) and constant?(exp.target)
`constant?` will check if it's a `Sexp` so you can skip the `sexp?` call.

2021-06-02 19:57 UTC, presidentbeef commented on lib/brakeman/checks/check_render.rb
> +  def known_renderable_class? class_name
Can you add a test for this? Thanks!

2021-06-10 23:03 UTC, merged

2021-06-10 23:03 UTC, presidentbeef commented
Thanks @bradparker!

2021-06-10 23:10 UTC, bradparker commented
No worries! Thanks :)